export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_RESET = "SEARCH_TRACKS_RESET";

export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const FETCH_NOW_PLAYING = "FETCH_NOW_PLAYING";
export const FETCH_NOW_PLAYING_SUCCESS = "FETCH_NOW_PLAYING_SUCCESS";

export const LOAD = "LOAD";

export const UPDATE_TOKEN_SUCCESS = "UPDATE_TOKEN_SUCCESS";

export const QUEUE_TRACK = "QUEUE_TRACK";
export const FETCH_QUEUE = "FETCH_QUEUE";
export const FETCH_QUEUE_SUCCESS = "FETCH_QUEUE_SUCCESS";

export const GROUP_JOIN = "GROUP_JOIN";

export const PLAY_TRACK = "PLAY_TRACK";
export const PLAY_TRACK_SUCCESS = "PLAY_TRACK_SUCCESS";

export const SET_HOST_TOKEN = "SET_HOST_TOKEN";
export const SET_NAME = "SET_NAME";

export const VOTE_UP = "VOTE_UP";
export const VOTE_DOWN = "VOTE_DOWN";
export const VOTE_NEUTRAL = "VOTE_NEUTRAL";
