export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_TRACKS_SUCCESS = "SEARCH_TRACKS_SUCCESS";
export const SEARCH_TRACKS_RESET = "SEARCH_TRACKS_RESET";

export const FETCH_TRACK = "FETCH_TRACK";
export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";

export const LOAD = "LOAD";

export const UPDATE_TOKEN_SUCCESS = "UPDATE_TOKEN_SUCCESS";

export const QUEUE_TRACK = "QUEUE_TRACK";
export const QUEUE_UPDATE_LOCAL = "QUEUE_UPDATE_LOCAL";

export const GROUP_JOIN = "GROUP_JOIN";
